#!/usr/bin/env bash
# Write AniList Client Secret into the gitignored local Swift file (not Settings / not NEXT_PUBLIC).
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TARGET="$ROOT/ios/App/SaizenCore/Auth/AnilistSecret.local.swift"

if [[ $# -ge 1 ]]; then
  SECRET="$1"
else
  echo -n "Paste AniList Client Secret (input hidden): "
  # shellcheck disable=SC2162
  read -s SECRET
  echo
fi

SECRET="$(printf '%s' "$SECRET" | tr -d '\r\n' | sed -E "s/^['\"]|['\"]$//g")"
if [[ -z "$SECRET" ]]; then
  echo "Empty secret — aborting."
  exit 1
fi

# Escape for Swift string literal
ESCAPED="$(printf '%s' "$SECRET" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g')"

cat > "$TARGET" <<EOF
import Foundation

/// LOCAL ONLY — gitignored. Generated by scripts/set-anilist-secret.sh
enum AnilistSecretLocal {
  static let value: String? = "${ESCAPED}"
}
EOF

echo "Wrote $TARGET"
echo "Run: pnpm sync:ios  (or bash scripts/sync-swift-into-cap.sh) then Clean Build in Xcode."
